### ISSUE TITLE
write file question

### ISSUE THREAD

**Issue by shizenghua** [paiden/Nett#32]
hello,when i write file,how can i update a node,if the node is set in the file?

**Comment by paiden** [comment]
Im not sure what you mean. Can you describe your issue with a small code example?

**Comment by shizenghua** [comment]
in my toml file  
[test]
a="123"
b="456"
i want to change the  a node "123"  to   "789",  then write to the toml file.
how can i change it?

**Comment by paiden** [comment]
I think what you try to do is:
```csharp
TomlTable tbl = Toml.ReadFile("myfile.toml");
Assert(tbl.Get<string>("a") == "123");
tbl["a"] = "789"
Toml.WriteFile(tbl, "myfile.toml") // overwrite with modified content
```
I inspected my API and this currently is not possible in a clean manner. Currently there is no API to change the value of TOML table row (at least when using the generic TomlTable data structure instead of a strongly typed CLR object). A possible workaround would be:

```csharp
var tbl = Toml.ReadFile("myfile.toml");
var dict = tbl as IDictionary<string, TomlObject>;
dict["a"] = tbl.CreateAttachedValue("123");
```
or
```csharp
var tbl = Toml.ReadFile("myfile.toml");
tbl.Remove("a");
tbl.AddValue("a", "123");
```

But I will definitely add a dedicated update method in the near future.

**Comment by Splamy** [comment]
I don't know if this is doable, but it would be nice if there also was an option to also preserve whitespaces when writing back to the file. Or at least a few options to specify how to format the output
Toml is a pretty nicely human-readable format, but it must be formatted accordingly for that.
Currently formatted toml gets squached together, are out of order and some comments get lost.

**Comment by paiden** [comment]
API for v0.8.0 got new methods that allow to update table rows (values)

@Splamy This does not belong into this issue and is a large topic on its own (will be my workload for the upcoming months). In fact nearly all of my 0.9.0 backlog items are linked to the topic of formatting the TOML file contents in both directions (read & write). So I'll close this issue here.
