### ISSUE TITLE
FSharp support

### ISSUE THREAD

**Issue by darting** [paiden/Nett#50]
When I use Nett in F# to write a list to file, I got this error `System.Reflection.TargetParameterCountException: Parameter count mismatch`. Even I convert to ResizeArray, still same.

```f#
Toml.WriteFile([ "test" ] |> ResizeArray, "test.toml")
```

Thanks

### update
I think I shouldn't write a list to toml directly. The following code is works:
```f#
let toDict (items : ('K * 'V) seq) = 
    Seq.fold (fun (s : Dictionary<'K, 'V>) i -> s.Add i; s) (Dictionary<'K, 'V>()) items

Toml.WriteFile(toDict  [ "a", [ 1; 2; 3 ] ], "test.toml")
```

**Comment by darting** [comment]
```f#
let settings = dict [ "a", [ 1; 2; 3 ] ]
Toml.WriteFile(settings, "test.toml")
```

Hmm write empty content

**Comment by darting** [comment]
Not support decimal type:
```f#
type Test = {
    Money : decimal
}

Toml.WriteFile({ Money = 10m }, "test.toml")
```

**Comment by paiden** [comment]
Ad1.) Only Dictionary<string object> or custom classes/structs can be written. I admit, the error message is not very good and may try to improve that in the future.
Ad2.) ? I'm not familiar with F#. What type has the settings object in that case? For Nett to understand it it has to be of type IDictionary or IDictionary<string, object>.
Ad3.) Decimal is not supported out of the box. This is by design. In the documentation https://github.com/paiden/Nett#handle-non-toml-types-via-custom-converters there is some documentation on how you can enable handling of the decimal type.
