### ISSUE TITLE
2d array doesn't serialize(Maybe not supported?)

### ISSUE THREAD

**Issue by drojf** [paiden/Nett#54]
```
class Unsupported 
{
    public int[,] array2d { get; set; }
}
```
```
Unsupported unsupportedClass = new Unsupported()
{
    array2d = new int[,] { {1, 2}, {3, 4} },
};

Toml.WriteFile(unsupportedClass, "test.toml");
var readback = Toml.ReadFile<Unsupported>("test.toml");
```

With the above code I would expect the output TOML to be 
```
array2d = [[1, 2], [3, 4]]
```

However I get
```
array2d = [1, 2, 3, 4]
```

And when deserializing I get " System.ArgumentException: 'Object of type 'System.Int32[]' cannot be converted to type 'System.Int32[,]'.' "

For my use case I just want a 2d array so that it can be edited easily by hand, rather than having a jagged array (which works fine), or an array of classes (which would produce an array of dicts).

EDIT: I'm guessing i'm meant to make a custom converter which produces the output I want, I just wasn't sure whether this was a bug or not.

EDIT2: After reading the custom conversion information, it seems better that I write a custom converter for an array of classes.

EDIT3: I tried the same thing with List<List<int>> and I couldn't get it to work (hang on, I didn't read the bit about the constructor?), but if I use the "generic TomlTable structure" api then I can read it in...I'll just use that for now. 

EDIT4: Looks like I can readback List<List<int>> but can't write it - I get " System.Reflection.TargetParameterCountException: 'Parameter count mismatch.' " when writing (using the same example as above, but using List<List<int> instead of int[,]. I got everything working the way I want (since I don't care about writing files for my use case).

**Comment by paiden** [comment]
Although multidimensional arrays are still **not** supported I classify this issue as fixed because Nett now can handle nested lists and **jagged arrays**. That Nett could not handle jagged arrays was IMHO the real issue here.

e.g. Nett can handle this:

```csharp
public class MArray
{
  public int[][] A2D { get; set; } = { new int[] { 1, 2 }, new int[] { 3, 4 } };
}
```

Multidimensional  arrays do not align that well with the array specification of TOML. Jagged arrays are suited much better. 

It is not impossible to support multidimensional arrays in Nett but IMHO supporting them adds too much complexity for what I consider a 'corner' use case. Bidirectional array type mapping with reflection only information gets complex and messy very quickly.

**Comment by drojf** [comment]
Agreed. I didn't (and I don't think others) will care about multidimensional arrays anyway - I was just trying to figure out how to do list of lists in TOML. If really needed, you could always write a wrapper around them to convert them to jagged arrays.

However, it would be nice if there were a list of natively supported/unsupported type examples on the front Readme.md, otherwise people may still try to use the wrong type as they don't know which C# type is meant to match to which TOML type.

Something like:

| toml          | c#                                                                              |
|---------------|---------------------------------------------------------------------------------|
| `[[1,2],[3,4]]` |  `new int[][] { new int[] { 1, 2 }, new int[] { 3, 4 } };` |

**Comment by ZenoArrow** [comment]
Just to say, regarding "I didn't (and I don't think others) will care about multidimensional arrays anyway", I would be interested in working with multidimensional arrays.

I've written a PowerShell script to validate that I can pull values out of multidimensional arrays using Nett, which is a bit cumbersome but is working (may be cumbersome due to my lack of awareness about the Nett library), but I'll be treating TOML as a read-only data format for the time being. I appreciate that if "Multidimensional arrays do not align that well with the array specification of TOML" then this would be something better addressed in the spec first, but just writing this to suggest that there is interest in this feature.

**Comment by paiden** [comment]
First version of this doc added at: http://paiden.github.io/Nett/articles/typeconv.html
