### ISSUE TITLE
Nett.StrongNamed 0.9.2

### ISSUE THREAD

**Issue by queil** [paiden/Nett#62]
Hi @paiden, is there a chance for a strong named version of 0.9.2? I want to use it in a VS Extension.

**Comment by queil** [comment]
@paiden ?

**Comment by paiden** [comment]
Sorry. I do not have much time at the moment for my hobby projects, so it can take some time until I reply.

Originally I planned to completely drop StrongNaming support, as it is quite some pain in the build process and also the secrets management is not much fun in OS projects (strong naming was the reason, the package publishing process is not fully automated yet).

But as always, when you drop something, someone comes a along who needs that 'feature' ;).

I'm currently investigating a better way to do the signing during build that at least should keep the build simple. If that works out, a strong named version of Nett 0.9.2 should be available within the next few days.

**Comment by Splamy** [comment]
I don't need strong naming, but maybe this helps.
In this [Talk](https://youtu.be/hLFyycJVo0I?t=1470) (24:30 - 27:00) Immo Landwerth, as well as this [MSDN](https://docs.microsoft.com/en-us/dotnet/framework/app-domains/strong-named-assemblies) article suggest to simply check in the public and private key, as strong naming is not a security feature anyway.

(From a slide in the talk:)
![image](https://user-images.githubusercontent.com/6502527/46904415-f5b55580-cee3-11e8-8d90-63b517dff582.png)

**Comment by paiden** [comment]
@Splamy Thx for the video, nice session I missed from this years .Net conf.

But currently I cannot completely agree to the statement 'DO strong name your libraries'. This statement may be OK if you have a single library. But as soon as you have a dependency tree IMHO the whole strong naming mechanism starts to break down for nuget dependencies, because it breaks any semantic versioning mechanisms.

Lets assume I release Nett v1.0.0 and Nett.Coma 1.0.0

I find a bug in Nett v1.0.0, fix it and create Nett v1.0.1 bugfix release. If Nett and Nett.Coma are strong named the lib consumer has to add the correct binding redirects or upgrade also Nett.Coma to v1.0.1 which I have to create although nothing was changed in Nett.Coma, expect the ASM reference. 

That's the reason why i provided 2 packages. For users that do not need strong naming, use the non strong named version and .Net will not complain with weird manifest exceptions. 

Otherwise use Nett.StrongNamed and you - as the consumer - have to know that you also need to upgrade Nett.Coma or add the correct binding redirects to make your application work at runtime.

Just StrongNaming all libs and checking in the *.snk would definitely be the easiest way for me. But I really fear that this will produce some confusion for the users of Nett.

In the video I did not see anything about managing lib dependency trees. 

@Splamy @queil What are your thoughts on this? Should I just strong name Nett in general or keep the approach of providing 2 packages versions... Am I missing something here?

**Comment by queil** [comment]
@paiden What I've done so far for my project - I have got a non-strong named version and I've created another project which has just links to the original files but it's strong named. So that way I can easily build both always and keep separate streams. I am not sure if it makes sense (might be too naive)..

**Comment by paiden** [comment]
For now I will keep 2 separate packages. 

http://nickberardi.com/json-net-strong-naming-and-nuget-woes/ and https://raygun.com/thinktank/suggestion/3289 show that simply strong naming .net libs also has its issues.

IMHO the 2 packages approach is more flexible. My extended build script also ensures, that all package versions are published on each release.
