### ISSUE TITLE
Config<T>.Get does not provide a way to differentiate between a missing key or malformed TOML

### ISSUE THREAD

**Issue by ckpearson** [paiden/Nett#74]
When presented with a config similar to:

```csharp
public class MyConfig
{
   public MyTableConfig[] MyTable {get;set;}
}
```

and the relevant TOML:

```toml
[[MyTableConfig]]
Key = 'val'
[[MyTableConfig]]
Key = 'val'
```

If the TOML doesn't contain any of the tables (a valid possibility in my scenario), the call to `Config<MyConfig>.Get(c => c.MyTableConfig)` throws an `InvalidOperationException` to indicate that the key isn't there - this behaviour is fine, it can be caught and handled.

The issue however is when the TOML for one of these tables is malformed, e.g.:

```toml
[[MyTableConfig]]
Key = 'val'

[[MyTableConfig]]
Key = 1
```

Whereby the `Key` property on `MyTableConfig` is a string without an implicit conversion configured (or indeed if the TOML is otherwise malformed), this similarly throws an `InvalidOperationException` containing details of either the malformed TOML or an internal issue such as a casting error.

Curiously, accessing the property against the `Config<T>.Unmanaged()` instance exhibits variable behaviour too:

1. If the key isn't present, accessing the property just returns the default value (assigned or otherwise) for that property
2. If the key is malformed, accessing the property throws an exception containing details of the malformed TOML

It would be helpful if these exceptions had different types (e.g. `KeyNotFoundException` and whatever might best suit malformed data), or if there was an alternative mechanism to retrieve validation data for arbitrary keys.

I've been able to work around this by:

1. Peeking at the value on the "Unmanaged" instance inside a try block that continues the throw as it represents malformed data
2. Then calling `.Get(c => c.Key)` and handling the happy / exception paths as necessary.

**Comment by paiden** [comment]
Puh that's a tricky use case. I think this will require some discussion.

After first quick thoughts I would argue the following way.

1. That `Config<MyConfig>.Get(c => c.MyTableConfig)` throws an `InvalidOperationException` is wrong. It should just deliver the default value (null / empty list or array, depending on how the data class is coded) as the class prop and not a table row directly is accessed.

2. The TOML fragment 
```toml
[[MyTableConfig]]
Key = 'val'

[[MyTableConfig]]
Key = 1
```
IMO is not malformed. At least I can't find anything in the TOML spec that would say otherwise. Although the [Array of tables](https://github.com/toml-lang/toml#array-of-tables) spec is a little bit vague in various points.

But here the mapping from a valid TomlTable to a object data structure fails as the types do not match and so the `InvalidOperationException` here is the correct thing to do.

3. I can understand the desire to get better error messages or do validation on the TOML file. But I think for this the Unmanaged() thing is not very well suited.

Probably exposing the underlying (merged) TOML table via a `TomlTable GetTable()` or something like that would be better suited to do these things. You can check for keys, enumerate all rows etc. with that it should be possible to do quite everything you want.

**Comment by paiden** [comment]
Applied improvement in 0.12.0. 

If still not satisfying new issue should be opened.
