### ISSUE TITLE
Nett cannot parse int as TomlFloat

### ISSUE THREAD

**Issue by miere43** [paiden/Nett#8]
```c#
public class MyObject
{
    public float MyFloat { get; set; }
}

public class Program
{
    static void Main(string[] args)
    {
        MyObject obj = new MyObject();
        obj.MyFloat = 123; // <= look here
        
        string output = Toml.WriteString<MyObject>(obj);
        // ok
        MyObject parsed = Toml.ReadString<MyObject>(output);
        // InvalidOperationException: Cannot convert from type 'int' to 'TomlFloat'.
    }
}
```

If you change ```MyFloat``` to non-int value like this: ```obj.MyFloat = 123.45f;``` then everything works fine.

**Comment by miere43** [comment]
Are you sure this is right fix for this? Toml is designed to be user-editable, and when someone removes float delimiter everything breaks again.

```c#
{
    string abc = "SomeFloat = 1" + Environment.NewLine;
    TomlTable table = Toml.ReadString(abc);
    float val = table.Get<float>("SomeFloat");
    // InvalidCastException: Unable to convert type "Nett.TomlInt" to type "Nett.TomlFloat".
}

{
    string abc = "One = 1" + Environment.NewLine;
    Testy testy = Toml.ReadString<Testy>(abc);
    // InvalidOperationException: Cannot convert from type 'int' to 'TomlFloat'.
}
```

**Comment by paiden** [comment]
Yes I'm quite sure this is correct. The TOML spec states: 

> A float consists of an integer part (which follows the same rules as integer values) followed by a fractional part and/or an exponent part.

My understanding is, that a float must have a fractional part otherwise it is not float (also see examples). So the TOML that was written by my serializer was invalid as it wrote an int instead of a float.

The scenario you describe also doesn't directly relate to the reading/writing of TOML anymore, but more to the process of mapping a TomlTable to a CLR type. As I'm not a big fan of implicit casts I currently disallow the use case you described. 

But I will think about, if it would make sense to give the user the ability to enable implicit casts via the ConfigApi or in some other form. But this would be a enhancement => another issue and not the same as this one here.

**Comment by miere43** [comment]
I don't get why you look at this problem from such point of view, but isn't it sounds weird that you can't convert int to float because it doesn't contain fractional part?
```c#
float val = Toml.Get<float>("SomeFloat");
//                   ↑↑↑↑↑
```
As you can see I **explicitly** showing that I want to get float value, then why Nett cannot convert int to float? I don't get it why I should take cast exception thrown into my face.

**Comment by paiden** [comment]
By the current design of the API, this line doesn't read as 

> Give me the TomlObject with key SomeFloat as a float

It needs to be read as
> Give me a TomlFloat with the key SomeFloat.

 As there is no TomlFloat with that key -> Exception.

What you want is something more like `GetAs<float>`. 

I can understand if you dislike that design, but as said I don't like implicit casts between arbitrary types and I don't plan to change this policy.The only implicit casts allowed are TomlType to corresponding CLR type so that someone doesn't need to mess around with TomlTypes trough their whole code base. 

But as said, I'm thinking about ways to enable your scenario. I already have some ideas for a nice solution that will integrate well with the current architecture and should require a single line of config code to activate it (without changing any Get<T> invocations).

**Comment by miere43** [comment]
Looking forward for this feature, I'll wait for it.
